#!/usr/bin/env bash
# Full project audit script (Phase 29 / P30-T2).
#
# Reports:
#   1. Inventory of ALL .lean files under Gdbh/ (including Gdbh/MathlibExtras/)
#      with line counts and the grand total.
#   2. Count of top-level theorem / lemma declarations.
#   3. Count of top-level def / noncomputable def declarations.
#   4. Genuine `sorry` / `admit` occurrences in `Gdbh/` (excluding
#      docstrings, single-line `--` comments, and string literals).
#   5. Genuine `axiom` declarations in `Gdbh/` (the project itself should
#      contain none; mathlib's `Classical.choice`, `Quot.sound`, `propext`
#      live in mathlib, not here).
#   6. Targeted `#print axioms` audit on the two headline theorems via
#      `lake env lean --stdin` (Path A Phase 5 headline + Path C P29-T3
#      headline).  The expected output is exactly
#      `[propext, Classical.choice, Quot.sound]`.
#
# The script is POSIX bash and is intended to be run from any cwd.  It
# does NOT invoke the long-running `audit_lean_axioms.py` (which stalls
# >30 minutes on the ~hundreds of audited theorems); instead it audits
# only the two named headlines.
#
# Output is written both to stdout and to
# `scripts/audit_full_report.txt`.

set -u

# Resolve repo root from this script's location so the audit runs from any cwd.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${REPO_ROOT}"

REPORT="${REPO_ROOT}/scripts/audit_full_report.txt"
mkdir -p "$(dirname "${REPORT}")"

# Helpers -------------------------------------------------------------------

emit() {
  printf '%s\n' "$*"
  printf '%s\n' "$*" >> "${REPORT}"
}

emit_section() {
  emit ""
  emit "=========================================================="
  emit "$1"
  emit "=========================================================="
}

# Reset the report file.
: > "${REPORT}"

emit "Full project audit (P30-T2)"
emit "Repository:      ${REPO_ROOT}"
emit "Report path:     ${REPORT}"
emit "Generated by:    scripts/audit_full.sh"
emit "Date:            $(date -u +'%Y-%m-%dT%H:%M:%SZ')"

# 1. File inventory --------------------------------------------------------

emit_section "1. .lean file inventory under Gdbh/ (including MathlibExtras/)"

TMP_FILES="$(mktemp)"
# Include every .lean under Gdbh/ (recursive: catches Gdbh/MathlibExtras/).
find Gdbh -type f -name '*.lean' | LC_ALL=C sort > "${TMP_FILES}"

NUM_FILES="$(wc -l < "${TMP_FILES}" | tr -d ' ')"
TOTAL_LINES=0
while IFS= read -r f; do
  LINES="$(wc -l < "${f}" | tr -d ' ')"
  TOTAL_LINES=$((TOTAL_LINES + LINES))
  printf '  %6d  %s\n' "${LINES}" "${f}" >> "${REPORT}"
done < "${TMP_FILES}"

emit ""
emit "  Total Lean files under Gdbh/:  ${NUM_FILES}"
emit "  Total lines under Gdbh/:       ${TOTAL_LINES}"

# Top-level Gdbh.lean barrel (informational; not part of the Gdbh/ folder
# but is the project's main import roll-up).
if [[ -f "${REPO_ROOT}/Gdbh.lean" ]]; then
  ROOT_LINES="$(wc -l < "${REPO_ROOT}/Gdbh.lean" | tr -d ' ')"
  emit "  Root Gdbh.lean barrel:         ${ROOT_LINES} lines"
fi

# 2. Theorem / lemma counts ------------------------------------------------

emit_section "2. theorem / lemma declarations under Gdbh/"

# Top-level (column 0) `theorem` / `lemma` keywords.  The same regex the
# Phase 19 audit script used; this catches `protected theorem` / `private
# theorem` as well.
THEOREM_RAW="$(
  grep -rn '^theorem\b\|^lemma\b\|^protected theorem\b\|^protected lemma\b\|^private theorem\b\|^private lemma\b' \
    Gdbh/ || true
)"
THEOREM_COUNT=0
if [[ -n "${THEOREM_RAW}" ]]; then
  THEOREM_COUNT="$(printf '%s\n' "${THEOREM_RAW}" | grep -c .)"
fi
emit "  total top-level theorem / lemma declarations: ${THEOREM_COUNT}"

# 3. def counts ------------------------------------------------------------

emit_section "3. def / noncomputable def declarations under Gdbh/"

DEF_RAW="$(
  grep -rn '^def\b\|^noncomputable def\b\|^protected def\b\|^private def\b' \
    Gdbh/ || true
)"
DEF_COUNT=0
if [[ -n "${DEF_RAW}" ]]; then
  DEF_COUNT="$(printf '%s\n' "${DEF_RAW}" | grep -c .)"
fi
emit "  total top-level def declarations: ${DEF_COUNT}"

# 4. sorry / admit ---------------------------------------------------------

emit_section "4. genuine sorry / admit occurrences in Gdbh/"

# Preferred path: run `audit_lean_source.py`, which masks block comments
# and string literals properly via a state machine.  Fall back to the
# heuristic grep pipeline if Python is unavailable.
GENUINE_SORRY_COUNT=0
GENUINE_ADMIT_COUNT=0
AUDIT_LEAN_SOURCE="${REPO_ROOT}/audit_lean_source.py"
if command -v python3 >/dev/null 2>&1 && [[ -f "${AUDIT_LEAN_SOURCE}" ]]; then
  emit "  -- using audit_lean_source.py (masked comments + strings) --"
  AUDIT_OUT="$(mktemp)"
  if python3 "${AUDIT_LEAN_SOURCE}" > "${AUDIT_OUT}" 2>&1; then
    AUDIT_RC=0
  else
    AUDIT_RC=$?
  fi
  # audit_lean_source.py prints `FAIL: <path>:line:col: <token>: <line>` for
  # each hit.  Token is one of axiom / constant / opaque / unsafe / sorry / admit.
  GENUINE_SORRY="$(grep -E '^FAIL: [^:]+:[0-9]+:[0-9]+: sorry:' "${AUDIT_OUT}" || true)"
  GENUINE_ADMIT="$(grep -E '^FAIL: [^:]+:[0-9]+:[0-9]+: admit:' "${AUDIT_OUT}" || true)"
  GENUINE_AXIOM_TXT="$(grep -E '^FAIL: [^:]+:[0-9]+:[0-9]+: axiom:' "${AUDIT_OUT}" || true)"
  if [[ -z "${GENUINE_SORRY}" ]]; then
    emit "    [OK] no genuine 'sorry' occurrences"
  else
    GENUINE_SORRY_COUNT="$(printf '%s\n' "${GENUINE_SORRY}" | grep -c .)"
    emit "    [WARN] ${GENUINE_SORRY_COUNT} genuine sorry occurrence(s):"
    printf '%s\n' "${GENUINE_SORRY}" | sed 's/^/      /' >> "${REPORT}"
  fi
  if [[ -z "${GENUINE_ADMIT}" ]]; then
    emit "    [OK] no genuine 'admit' occurrences"
  else
    GENUINE_ADMIT_COUNT="$(printf '%s\n' "${GENUINE_ADMIT}" | grep -c .)"
    emit "    [WARN] ${GENUINE_ADMIT_COUNT} genuine admit occurrence(s):"
    printf '%s\n' "${GENUINE_ADMIT}" | sed 's/^/      /' >> "${REPORT}"
  fi
  if [[ -n "${GENUINE_AXIOM_TXT}" ]]; then
    emit "    [WARN] audit_lean_source.py also flagged axiom-class tokens:"
    printf '%s\n' "${GENUINE_AXIOM_TXT}" | sed 's/^/      /' >> "${REPORT}"
  fi
  rm -f "${AUDIT_OUT}"
else
  # Fallback: heuristic grep pipeline (audit_phase19 lineage).
  emit "  -- python3 / audit_lean_source.py unavailable; using grep fallback --"
  SPEC_SORRY="$(
    grep -rn '\bsorry\b' Gdbh/ \
      | grep -v '^[^:]*:[^:]*:.*--' \
      | grep -v 'admits\|admit\.\|admit witnesses\|admit the' \
      | grep -v "'sorry'\|\"sorry\"\|'admit'\|\"admit\"" \
      | grep -v 'no `sorry`' \
      || true
  )"
  SPEC_ADMIT="$(
    grep -rn '\badmit\b' Gdbh/ \
      | grep -v '^[^:]*:[^:]*:.*--' \
      | grep -v 'admits\|admit\.\|admit witnesses\|admit the' \
      | grep -v "'sorry'\|\"sorry\"\|'admit'\|\"admit\"" \
      | grep -v 'no `sorry`' \
      || true
  )"
  GENUINE_SORRY="$(
    printf '%s\n' "${SPEC_SORRY}" \
      | grep -E '\bsorry\b' \
      | grep -v '`sorry`\|`admit`' \
      | grep -v "'sorry'\|\"sorry\"\|'admit'\|\"admit\"" \
      || true
  )"
  GENUINE_ADMIT="$(
    printf '%s\n' "${SPEC_ADMIT}" \
      | grep -E '\badmit\b' \
      | grep -v '`sorry`\|`admit`' \
      | grep -v "'sorry'\|\"sorry\"\|'admit'\|\"admit\"" \
      || true
  )"
  if [[ -z "${GENUINE_SORRY}" ]]; then
    emit "    [OK] no genuine 'sorry' occurrences"
  else
    GENUINE_SORRY_COUNT="$(printf '%s\n' "${GENUINE_SORRY}" | grep -c .)"
    emit "    [WARN] ${GENUINE_SORRY_COUNT} genuine sorry occurrence(s):"
    printf '%s\n' "${GENUINE_SORRY}" | sed 's/^/      /' >> "${REPORT}"
  fi
  if [[ -z "${GENUINE_ADMIT}" ]]; then
    emit "    [OK] no genuine 'admit' occurrences"
  else
    GENUINE_ADMIT_COUNT="$(printf '%s\n' "${GENUINE_ADMIT}" | grep -c .)"
    emit "    [WARN] ${GENUINE_ADMIT_COUNT} genuine admit occurrence(s):"
    printf '%s\n' "${GENUINE_ADMIT}" | sed 's/^/      /' >> "${REPORT}"
  fi
fi

# 5. axiom declarations ----------------------------------------------------

emit_section "5. axiom declarations in Gdbh/"

AXIOM_RAW="$(grep -rn '\baxiom\b' Gdbh/ || true)"
# A real `axiom` declaration starts with `axiom` followed by an identifier
# and a colon.  Anything else (`axiom-clean`, `the axiom Classical.choice`,
# etc.) is prose and is excluded by the regex below.
AXIOM_DECLS="$(
  printf '%s\n' "${AXIOM_RAW}" \
    | grep -E ':[[:space:]]*(axiom|@\[[^]]*\][[:space:]]*axiom)[[:space:]]+[A-Za-z_][A-Za-z0-9_.]*[[:space:]]*[:({\[]' \
    || true
)"

if [[ -z "${AXIOM_DECLS}" ]]; then
  emit "  [OK] no 'axiom' declarations found in Gdbh/"
  AXIOM_DECL_COUNT=0
else
  AXIOM_DECL_COUNT="$(printf '%s\n' "${AXIOM_DECLS}" | grep -c .)"
  emit "  [WARN] ${AXIOM_DECL_COUNT} axiom declaration(s):"
  printf '%s\n' "${AXIOM_DECLS}" | sed 's/^/    /' >> "${REPORT}"
fi

AXIOM_RAW_COUNT=0
if [[ -n "${AXIOM_RAW}" ]]; then
  AXIOM_RAW_COUNT="$(printf '%s\n' "${AXIOM_RAW}" | grep -c .)"
fi
emit "  total textual 'axiom' hits (including prose like 'axiom-clean'): ${AXIOM_RAW_COUNT}"

# 6. Targeted #print axioms on headlines -----------------------------------

emit_section "6. #print axioms on headline theorems (lake env lean --stdin)"

# Locate lake / lean.  Prefer an already-on-PATH `lake`; otherwise source
# elan's env (the standard install location).
LAKE="$(command -v lake 2>/dev/null || true)"
if [[ -z "${LAKE}" ]]; then
  if [[ -f "${HOME}/.elan/env" ]]; then
    # shellcheck disable=SC1091
    . "${HOME}/.elan/env"
    LAKE="$(command -v lake 2>/dev/null || true)"
  fi
fi

if [[ -z "${LAKE}" ]]; then
  emit "  [SKIP] lake not found on PATH and ~/.elan/env not present;"
  emit "         skipping the #print axioms step.  Install elan + a Lean"
  emit "         toolchain to enable the axiom audit."
else
  emit "  Using lake at:  ${LAKE}"
  # The two headlines audited:
  #   * Path A Phase 5 (RH-conditional binary Goldbach headline)
  #   * Path C P29-T3 (unconditional K-Goldbach, modulo HL §3.11 kernel + 3 bridges)
  HEADLINES=(
    "Gdbh.strongGoldbach_under_RH_phase5_reduced"
    "Gdbh.PathCKGoldbachUnconditional.pathC_kGoldbach_unconditional"
  )

  # Build a small Lean probe that imports the two headline modules and
  # emits `#print axioms` for each.  We feed it via --stdin so that no
  # temporary file is left lying around in the project tree.
  PROBE_INPUT="$(mktemp)"
  {
    printf 'import Gdbh.PathA_Final\n'
    printf 'import Gdbh.PathC_KGoldbachUnconditional\n\n'
    for thm in "${HEADLINES[@]}"; do
      printf '#print axioms %s\n' "${thm}"
    done
  } > "${PROBE_INPUT}"

  emit ""
  emit "  -- probe content --"
  sed 's/^/    /' "${PROBE_INPUT}" >> "${REPORT}"

  emit ""
  emit "  -- lake env lean --stdin output --"
  PROBE_OUTPUT="$(mktemp)"
  PROBE_ERROR="$(mktemp)"
  # `lake env lean --stdin` reads a .lean source from stdin and runs it.
  # The output of every `#print axioms` ends up on stdout.  We capture both
  # stdout and stderr so the audit also surfaces any build issues.
  if "${LAKE}" env lean --stdin < "${PROBE_INPUT}" \
        > "${PROBE_OUTPUT}" 2> "${PROBE_ERROR}"; then
    LEAN_RC=0
  else
    LEAN_RC=$?
  fi

  if [[ -s "${PROBE_OUTPUT}" ]]; then
    sed 's/^/    /' "${PROBE_OUTPUT}" >> "${REPORT}"
  fi
  if [[ -s "${PROBE_ERROR}" ]]; then
    emit ""
    emit "  -- stderr --"
    sed 's/^/    /' "${PROBE_ERROR}" >> "${REPORT}"
  fi

  emit ""
  emit "  lake env lean exit code: ${LEAN_RC}"

  # Classify each headline as OK / FAIL based on the axiom output.
  # Allowed axiom set: exactly {propext, Classical.choice, Quot.sound}.
  #
  # Lean's `#print axioms <thm>` emits, on success,
  #   'Gdbh.foo' depends on axioms: [propext, Classical.choice, Quot.sound]
  # with the bracketed list possibly wrapped onto subsequent indented lines.
  # We collapse continuation lines into a single logical record by joining
  # any line that does not itself start with a single quote into the
  # previous logical line.
  emit ""
  emit "  -- per-headline classification --"
  HEADLINE_OK_COUNT=0
  HEADLINE_FAIL_COUNT=0
  FLAT_OUTPUT="$(awk '
    /^.depends on axioms:/ { if (rec != "") print rec; rec=$0; next }
    /^.* depends on axioms:/ { if (rec != "") print rec; rec=$0; next }
    /^'"'"'/ { if (rec != "") print rec; rec=$0; next }
    { if (rec != "") rec=rec " " $0; else rec=$0 }
    END { if (rec != "") print rec }
  ' "${PROBE_OUTPUT}")"
  for thm in "${HEADLINES[@]}"; do
    LINE="$(printf '%s\n' "${FLAT_OUTPUT}" \
      | grep -F "'${thm}' depends on axioms:" || true)"
    if [[ -z "${LINE}" ]]; then
      emit "    [FAIL] ${thm} — no #print axioms output found"
      HEADLINE_FAIL_COUNT=$((HEADLINE_FAIL_COUNT + 1))
      continue
    fi
    # Extract the comma-separated list inside [...].
    AXIOMS="$(printf '%s\n' "${LINE}" \
      | sed -E "s/^'${thm}' depends on axioms:[[:space:]]*\[//; s/\][[:space:]]*$//")"
    UNEXPECTED="$(printf '%s\n' "${AXIOMS}" \
      | tr ',' '\n' \
      | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//' \
      | grep -v '^$' \
      | grep -vE '^(propext|Classical\.choice|Quot\.sound)$' \
      || true)"
    if [[ -z "${UNEXPECTED}" ]]; then
      emit "    [OK]   ${thm}  depends on axioms: [${AXIOMS}]"
      HEADLINE_OK_COUNT=$((HEADLINE_OK_COUNT + 1))
    else
      emit "    [FAIL] ${thm} — unexpected axioms:"
      printf '%s\n' "${UNEXPECTED}" | sed 's/^/             /' >> "${REPORT}"
      HEADLINE_FAIL_COUNT=$((HEADLINE_FAIL_COUNT + 1))
    fi
  done

  rm -f "${PROBE_INPUT}" "${PROBE_OUTPUT}" "${PROBE_ERROR}"
fi

rm -f "${TMP_FILES}"

# 7. Summary ---------------------------------------------------------------

emit_section "7. summary"

emit "  files:               ${NUM_FILES}"
emit "  lines:               ${TOTAL_LINES}"
emit "  theorems / lemmas:   ${THEOREM_COUNT}"
emit "  defs:                ${DEF_COUNT}"
emit "  sorry (genuine):     ${GENUINE_SORRY_COUNT}"
emit "  admit (genuine):     ${GENUINE_ADMIT_COUNT}"
emit "  axiom decls:         ${AXIOM_DECL_COUNT}"
if [[ -n "${LAKE:-}" ]]; then
  emit "  headlines OK:        ${HEADLINE_OK_COUNT:-0}"
  emit "  headlines FAIL:      ${HEADLINE_FAIL_COUNT:-0}"
else
  emit "  headlines:           skipped (no lake on PATH)"
fi

emit ""
emit "Audit complete.  Full report written to:"
emit "  ${REPORT}"
