#!/usr/bin/env bash
# Phase 19 final cleanliness audit (read-only).
#
# Reports:
#   1. Genuine `sorry` / `admit` occurrences in `Gdbh/` (excluding
#      docstrings, single-line `--` comments, and string literals).
#   2. Genuine `axiom` declarations in `Gdbh/` (the project itself should
#      contain none beyond mathlib's `Classical.choice`, `Quot.sound`,
#      `propext` -- those live in mathlib, not in `Gdbh/`).
#   3. All `.lean` files in `Gdbh/` with line counts.
#   4. (Optional) all theorems declared in `Gdbh/` via `grep`.
#
# Output is written both to stdout and to
# `scripts/audit_phase19_report.txt`.

set -u

# Resolve repo root from this script's location so the audit runs from any cwd.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${REPO_ROOT}"

REPORT="${REPO_ROOT}/scripts/audit_phase19_report.txt"
mkdir -p "$(dirname "${REPORT}")"

# Helpers -------------------------------------------------------------------

emit() {
  # Print to stdout and append to the report.
  printf '%s\n' "$*"
  printf '%s\n' "$*" >> "${REPORT}"
}

emit_section() {
  emit ""
  emit "=========================================================="
  emit "$1"
  emit "=========================================================="
}

# Reset the report file.
: > "${REPORT}"

emit "Phase 19 cleanliness audit"
emit "Repository:      ${REPO_ROOT}"
emit "Report path:     ${REPORT}"
emit "Generated by:    scripts/audit_phase19.sh"
emit "Date:            $(date -u +'%Y-%m-%dT%H:%M:%SZ')"

# 1. sorry / admit ----------------------------------------------------------

emit_section "1. Genuine sorry / admit occurrences in Gdbh/"

# Step 1a: the audit pipeline mandated by the task spec.
# We exclude:
#   - single-line `--` comment lines,
#   - `admits` and `admit.` prose hits,
#   - the literal-token forms 'sorry', "sorry", 'admit', "admit",
#   - the prose phrase "no `sorry`".
#
# This filter intentionally still surfaces backticked docstring mentions
# like `* No \`sorry\`, no \`axiom\`, no \`admit\`.`; the secondary
# filter below classifies which (if any) are genuine code.
SPEC_SORRY="$(
  grep -rn '\bsorry\b' Gdbh/ \
    | grep -v '^[^:]*:[^:]*:.*--' \
    | grep -v 'admits\|admit\.' \
    | grep -v "'sorry'\|\"sorry\"\|'admit'\|\"admit\"" \
    | grep -v 'no `sorry`' \
    || true
)"
SPEC_ADMIT="$(
  grep -rn '\badmit\b' Gdbh/ \
    | grep -v '^[^:]*:[^:]*:.*--' \
    | grep -v 'admits\|admit\.' \
    | grep -v "'sorry'\|\"sorry\"\|'admit'\|\"admit\"" \
    | grep -v 'no `sorry`' \
    || true
)"

emit "  -- spec pipeline (per task description) --"
if [[ -z "${SPEC_SORRY}" ]]; then
  emit "    [OK] spec pipeline reports no sorry hits"
else
  SPEC_SORRY_COUNT="$(printf '%s\n' "${SPEC_SORRY}" | grep -c .)"
  emit "    ${SPEC_SORRY_COUNT} sorry hit(s) survive the spec pipeline"
fi
if [[ -z "${SPEC_ADMIT}" ]]; then
  emit "    [OK] spec pipeline reports no admit hits"
else
  SPEC_ADMIT_COUNT="$(printf '%s\n' "${SPEC_ADMIT}" | grep -c .)"
  emit "    ${SPEC_ADMIT_COUNT} admit hit(s) survive the spec pipeline"
fi

# Step 1b: strict filter — count only hits that look like genuine code
# (not docstring backticked references).  A genuine `sorry`/`admit` in a
# Lean term position appears bare (no backticks, no quotes).  We drop all
# lines whose only matches for `sorry`/`admit` are backticked references
# (e.g. `\`sorry\``), quoted literals, or other prose mentions.
GENUINE_SORRY="$(
  printf '%s\n' "${SPEC_SORRY}" \
    | grep -E '\bsorry\b' \
    | grep -v '`sorry`' \
    | grep -v '`admit`' \
    | grep -v "'sorry'" \
    | grep -v '"sorry"' \
    | grep -v "'admit'" \
    | grep -v '"admit"' \
    || true
)"
GENUINE_ADMIT="$(
  printf '%s\n' "${SPEC_ADMIT}" \
    | grep -E '\badmit\b' \
    | grep -v '`sorry`' \
    | grep -v '`admit`' \
    | grep -v "'sorry'" \
    | grep -v '"sorry"' \
    | grep -v "'admit'" \
    | grep -v '"admit"' \
    | grep -v 'admit' \
    || true
)"
# Note: the final `grep -v 'admit'` for ADMIT looks odd but is intentional
# defensive code: after stripping backticked/quoted forms, any remaining
# bare 'admit' would be a real tactic and would survive *previous* filters
# rather than this one — keep this filter inert by accident.  Re-derive:
GENUINE_ADMIT="$(
  printf '%s\n' "${SPEC_ADMIT}" \
    | grep -E '\badmit\b' \
    | grep -v '`admit`' \
    | grep -v "'admit'" \
    | grep -v '"admit"' \
    | grep -v ' `sorry`,' \
    || true
)"

emit ""
emit "  -- strict filter (drops backticked/quoted prose mentions) --"

if [[ -z "${GENUINE_SORRY}" ]]; then
  emit "    [OK] no genuine 'sorry' occurrences"
  GENUINE_SORRY_COUNT=0
else
  GENUINE_SORRY_COUNT="$(printf '%s\n' "${GENUINE_SORRY}" | grep -c .)"
  emit "    [WARN] ${GENUINE_SORRY_COUNT} genuine sorry occurrence(s):"
  printf '%s\n' "${GENUINE_SORRY}" | sed 's/^/      /' | tee -a "${REPORT}"
fi

if [[ -z "${GENUINE_ADMIT}" ]]; then
  emit "    [OK] no genuine 'admit' occurrences"
  GENUINE_ADMIT_COUNT=0
else
  GENUINE_ADMIT_COUNT="$(printf '%s\n' "${GENUINE_ADMIT}" | grep -c .)"
  emit "    [WARN] ${GENUINE_ADMIT_COUNT} genuine admit occurrence(s):"
  printf '%s\n' "${GENUINE_ADMIT}" | sed 's/^/      /' | tee -a "${REPORT}"
fi

# 2. axioms ----------------------------------------------------------------

emit_section "2. axiom declarations in Gdbh/"

AXIOM_RAW="$(grep -rn '\baxiom\b' Gdbh/ || true)"
# A real `axiom` declaration starts with `axiom` (possibly preceded by
# whitespace or attributes) followed by an identifier and `:`.  Anything
# else (`axiom-clean`, `the axiom Classical.choice`, etc.) is prose.
AXIOM_DECLS="$(
  printf '%s\n' "${AXIOM_RAW}" \
    | grep -E ':[[:space:]]*(axiom|@\[[^]]*\][[:space:]]*axiom)[[:space:]]+[A-Za-z_][A-Za-z0-9_.]*[[:space:]]*[:({\[]' \
    || true
)"

if [[ -z "${AXIOM_DECLS}" ]]; then
  emit "  [OK] no 'axiom' declarations found in Gdbh/"
  AXIOM_DECL_COUNT=0
else
  AXIOM_DECL_COUNT="$(printf '%s\n' "${AXIOM_DECLS}" | grep -c .)"
  emit "  [WARN] ${AXIOM_DECL_COUNT} axiom declaration(s):"
  printf '%s\n' "${AXIOM_DECLS}" | sed 's/^/    /' | tee -a "${REPORT}"
fi

AXIOM_RAW_COUNT="$(printf '%s\n' "${AXIOM_RAW}" | grep -c .)"
emit "  total textual 'axiom' hits (including prose like 'axiom-clean'): ${AXIOM_RAW_COUNT}"

# 3. file inventory --------------------------------------------------------

emit_section "3. .lean files in Gdbh/ with line counts"

# Use a temp file rather than process substitution for portability.
TMP_FILES="$(mktemp)"
find Gdbh -type f -name '*.lean' | sort > "${TMP_FILES}"

NUM_FILES="$(wc -l < "${TMP_FILES}" | tr -d ' ')"
TOTAL_LINES=0
while IFS= read -r f; do
  LINES="$(wc -l < "${f}" | tr -d ' ')"
  TOTAL_LINES=$((TOTAL_LINES + LINES))
  printf '  %6d  %s\n' "${LINES}" "${f}" | tee -a "${REPORT}"
done < "${TMP_FILES}"
rm -f "${TMP_FILES}"

emit ""
emit "  Total Lean files in Gdbh/: ${NUM_FILES}"
emit "  Total lines across Gdbh/:  ${TOTAL_LINES}"

# 4. theorem inventory (optional) -----------------------------------------

emit_section "4. theorem declarations in Gdbh/ (optional inventory)"

THEOREM_HITS="$(grep -rn '^theorem\b\|^lemma\b\|^protected theorem\b\|^protected lemma\b' Gdbh/ || true)"
THEOREM_COUNT=0
if [[ -n "${THEOREM_HITS}" ]]; then
  THEOREM_COUNT="$(printf '%s\n' "${THEOREM_HITS}" | grep -c .)"
fi
emit "  total theorem/lemma declarations (top-level grep): ${THEOREM_COUNT}"

# 5. summary ---------------------------------------------------------------

emit_section "5. summary"

emit "  files:           ${NUM_FILES}"
emit "  lines:           ${TOTAL_LINES}"
emit "  sorry (genuine): ${GENUINE_SORRY_COUNT}"
emit "  admit (genuine): ${GENUINE_ADMIT_COUNT}"
emit "  axiom decls:     ${AXIOM_DECL_COUNT}"
emit "  theorems:        ${THEOREM_COUNT}"

emit ""
emit "Audit complete.  Full report written to:"
emit "  ${REPORT}"
